// mode_config.c
#include "mode_config.h"
#include "../../include/pqc_params.h"
#include <stdio.h>

// 전역 변수 정의
int MLKEM_CURRENT_MODE;

int MLKEM_K;
int MLKEM_ETA1;
int MLKEM_ETA2;
size_t MLKEM_POLYCOMPRESSEDBYTES;
size_t MLKEM_POLYVECCOMPRESSEDBYTES;
size_t MLKEM_POLYVECBYTES;
size_t MLKEM_INDCPA_MSGBYTES;
size_t MLKEM_INDCPA_PUBLICKEYBYTES;
size_t MLKEM_INDCPA_SECRETKEYBYTES;
size_t MLKEM_PUBLICKEYBYTES;
size_t MLKEM_SECRETKEYBYTES;
size_t MLKEM_CIPHERTEXTBYTES;
size_t MLKEM_INDCPA_BYTES;

// 모드에 따라 전역 변수 설정
void mlkem_set_mode(int mode) {
    // ML-KEM-512 설정
    if (mode == PQC_MODE_1) {
        MLKEM_CURRENT_MODE = PQC_MODE_1;
        MLKEM_K = MLKEM_512_K;
        MLKEM_ETA1 = MLKEM_512_ETA1;
        MLKEM_ETA2 = MLKEM_512_ETA2;
        MLKEM_POLYCOMPRESSEDBYTES = MLKEM_512_POLYCOMPRESSEDBYTES;
        MLKEM_POLYVECCOMPRESSEDBYTES = MLKEM_512_POLYVECCOMPRESSEDBYTES;
        MLKEM_POLYVECBYTES = MLKEM_512_POLYVECBYTES;
        MLKEM_INDCPA_MSGBYTES = MLKEM_512_INDCPA_MSGBYTES;
        MLKEM_INDCPA_PUBLICKEYBYTES = MLKEM_512_INDCPA_PUBLICKEYBYTES;
        MLKEM_INDCPA_SECRETKEYBYTES = MLKEM_512_INDCPA_SECRETKEYBYTES;
        MLKEM_PUBLICKEYBYTES = ML_KEM_512_PUBLIC_KEY_BYTES;
        MLKEM_SECRETKEYBYTES = ML_KEM_512_SECRET_KEY_BYTES;
        MLKEM_CIPHERTEXTBYTES = ML_KEM_512_CIPHERTEXT_BYTES;
        MLKEM_INDCPA_BYTES = MLKEM_512_POLYVECCOMPRESSEDBYTES + MLKEM_512_POLYCOMPRESSEDBYTES;
    }
    // ML-KEM-768 설정
    else if (mode == PQC_MODE_2) {
        MLKEM_CURRENT_MODE = PQC_MODE_2;
        MLKEM_K = MLKEM_768_K;
        MLKEM_ETA1 = MLKEM_768_ETA1;
        MLKEM_ETA2 = MLKEM_768_ETA2;
        MLKEM_POLYCOMPRESSEDBYTES = MLKEM_768_POLYCOMPRESSEDBYTES;
        MLKEM_POLYVECCOMPRESSEDBYTES = MLKEM_768_POLYVECCOMPRESSEDBYTES;
        MLKEM_POLYVECBYTES = MLKEM_768_POLYVECBYTES;
        MLKEM_INDCPA_MSGBYTES = MLKEM_768_INDCPA_MSGBYTES;
        MLKEM_INDCPA_PUBLICKEYBYTES = MLKEM_768_INDCPA_PUBLICKEYBYTES;
        MLKEM_INDCPA_SECRETKEYBYTES = MLKEM_768_INDCPA_SECRETKEYBYTES;
        MLKEM_PUBLICKEYBYTES = ML_KEM_768_PUBLIC_KEY_BYTES;
        MLKEM_SECRETKEYBYTES = ML_KEM_768_SECRET_KEY_BYTES;
        MLKEM_CIPHERTEXTBYTES = ML_KEM_768_CIPHERTEXT_BYTES;
        MLKEM_INDCPA_BYTES = MLKEM_768_POLYVECCOMPRESSEDBYTES + MLKEM_768_POLYCOMPRESSEDBYTES;
    }
    // ML-KEM-1024 설정
    else if (mode == PQC_MODE_3) {
        MLKEM_CURRENT_MODE = PQC_MODE_3;
        MLKEM_K = MLKEM_1024_K;
        MLKEM_ETA1 = MLKEM_1024_ETA1;
        MLKEM_ETA2 = MLKEM_1024_ETA2;
        MLKEM_POLYCOMPRESSEDBYTES = MLKEM_1024_POLYCOMPRESSEDBYTES;
        MLKEM_POLYVECCOMPRESSEDBYTES = MLKEM_1024_POLYVECCOMPRESSEDBYTES;
        MLKEM_POLYVECBYTES = MLKEM_1024_POLYVECBYTES;
        MLKEM_INDCPA_MSGBYTES = MLKEM_1024_INDCPA_MSGBYTES;
        MLKEM_INDCPA_PUBLICKEYBYTES = MLKEM_1024_INDCPA_PUBLICKEYBYTES;
        MLKEM_INDCPA_SECRETKEYBYTES = MLKEM_1024_INDCPA_SECRETKEYBYTES;
        MLKEM_PUBLICKEYBYTES = ML_KEM_1024_PUBLIC_KEY_BYTES;
        MLKEM_SECRETKEYBYTES = ML_KEM_1024_SECRET_KEY_BYTES;
        MLKEM_CIPHERTEXTBYTES = ML_KEM_1024_CIPHERTEXT_BYTES;
        MLKEM_INDCPA_BYTES = MLKEM_1024_POLYVECCOMPRESSEDBYTES + MLKEM_1024_POLYCOMPRESSEDBYTES;
    }
    else {
        fprintf(stderr, "오류: 지원되지 않는 모드 값 %d\n", mode);
        return -1;
    }
}